### ISSUE TITLE
How to setup HNS redirect

### ISSUE THREAD

**Issue by rafaelcastrocouto** [dnslive/dnslive-webhost#1]
Hi, first gratz for the service and the repository.
Second, I'm not sure if this is the right place for this issue so feel free to close it and point me to a proper rep.

I have followed this small tutorial on how to create a redirect:
```
DNS.live Free URL Redirection
Set your DNS hostname record to point to 66.175.213.205
Create a TXT record with the following values:
r=http://url
```

How can I create an A record to set my DNS hostname record to point to 66.175.213.205?
I've bought my domain with namebase, and in their front-end they allow me to create NS, DS and TXT records. It's possible to set a NS to point to Namebase's nameservers (ns1: 44.231.6.183) and from there they allow me to create A records, but no @ is allowed.

Can you help me setup a domain redirect from a namebase HNS domain please (if it's possible).

**Comment by realrasengan** [comment]
Hi rafaelcastrocouto,

Thank you!  This is definitely a fine place to ask questions.

You can absolutely set up the NS on Namebase's servers.  The @ is a wildcard, so you may be able to simply put 'yourzone.' with the trailing '.' being important to set a record for your TLD host.  It may look something like:

yourzone.  IN A 66.175.213.205
yourzone.  IN TXT "r=http://somesite/"

Once you set the A record to point to DNS Live's URL Redirection server and setup the TXT record for that (both on chain or in your dns zone record will work fine with our service in terms of the TXT record for the top level domain), you should be all set!

Hope this helps, and please do not hesitate to ask if you have any further questions.

Thank you for choosing DNS Live's Free DNS URL Redirection service for your URL redirection needs!

Cheers,
Andrew

**Comment by rafaelcastrocouto** [comment]
Thanks a lot for your quick response. Just after posting this question I setup my DNS with the following registers:
```
Blockchain:
Type	Name	Value
NS 		ns1 	44.231.6.183
TXT			 	r=https://foda-app.herokuapp.com/
Namebase:
TXT		www 	r=https://foda-app.herokuapp.com/
A		www		66.175.213.205
```
And before I tried out your suggestion I tested and it was already working. 
It does a quick redirect to `www.myzone./` and them it goes to my heroku app, so I guess I'll add your suggestions as well.

For those following this, it's important to remember you need to setup your network DNS settings for this to work. I'm using [nextDNS.io](https://nextdns.io/)

Thanks a lot for helping out.
